# Computer = codemaker / Player = codebreaker

# all the possible combinations
possible_numbers = (1111..6666).to_a

# random number generated by the computer
computer_random_code = possible_numbers.shuffle.first.to_s

# R = number of red pegs (position & number are both right)
# W = number of white pegs (only the number is right)
hint = {R: 0, W: 0}

computer_score = 0
player_score = 0
rounds = 12

# Play game
puts "Welcome to MASTERMIND."
puts "You must guess a 4 digit number between 1111 and 6666."
puts "Enter 'stop' to finish the game"


while rounds > 0 do
  puts "Round #{13-rounds}/12"
  puts "Enter a number: "
  player_answer = gets.chomp
  if player_answer.downcase == "stop"
    exit
  elsif player_answer.to_i.digits.count != 4
    puts "Enter a valid 4-digit number"
  else
    computer_random_code.chars.each_with_index do |digit, index|
      # if the number and position is the same, increment R
      if digit == player_answer[index]
        hint[:R] += 1
      # if only the number is the same, increment W
      elsif player_answer.include?(digit)
        hint[:W] += 1
      # otherwise display the hint and play the next round
      else
        next
      end
    end
    if player_answer == computer_random_code
      puts "Nailed it!"
      puts "Computer Score: #{computer_score}"
      exit
    else
      puts hint
      hint = {R: 0, W: 0}
      computer_score += 1
    end
    rounds -= 1
    if rounds == 0
      puts "Rounds up! You didn't guess it."
      puts "The Secret Code was: #{computer_random_code}"
      computer_score += 1
      puts "Computer Score: #{computer_score}"
    end
  end
end
